### PR TITLE
add transactionnel template mailjet

### PR DESCRIPTION
**Pull request by TonyTR**
@ScottAgirs  okay for the code … on the other hand, I can’t retrieve the HTMLPart in a transactional mailjet model.. une idée ? ;)

### CODE REVIEW

**Comment by TonyTR** [comment]
@ScottAgirs ok i find ... add : 
```
 Variables: {
       html: html
 }, 
```
in index.js and {{var:html}} in transactional mailjet model ... I add this

**Comment by ScottAgirs** [comment]
Hey @TonyTR thank you for the PR, could you please add documentation example for this?

**Comment by TonyTR** [comment]
hello @ScottAgirs i added the configuration details into the readme -> https://github.com/TonyTR/strapi-provider-email-mailjet/blob/develop/README.md

**Comment by TonyTR** [comment]
on the other hand, I have a recurring problem: the emails enter in a list automatically switch to it "excluded". i contacted the mailjet support and they tell me it came from the plug but I can't fix it

**Comment by ScottAgirs** [comment]
Hey @TonyTR please feel free to re-open, if this is still relevant, will close for now.

Also updated package for V4 is out - [v/4.0.0](https://www.npmjs.com/package/strapi-provider-email-mailjet/v/4.0.0)

**Pull request closed without merging**
